//BNS
export const FETCHING_NEWS_BNS = 'FETCHING_NEWS_BNS';
export const FETCHED_NEWS_BNS = 'FETCHED_NEWS_BNS';
//export const ERROR_BNS = 'ERROR_BNS';

//ENT
export const FETCHING_NEWS_ENT = 'FETCHING_NEWS_ENT';
export const FETCHED_NEWS_ENT = 'FETCHED_NEWS_ENT';
//export const ERROR_ENT = 'ERROR_ENT';

//HCKR
export const FETCHING_NEWS_HCKR = 'FETCHING_NEWS_HCKR';
export const FETCHED_NEWS_HCKR = 'FETCHED_NEWS_HCKR';
//export const ERROR_HCKR = 'ERROR_HCKR';

// IND
export const FETCHING_NEWS_IND = 'FETCHING_NEWS_IND';
export const FETCHED_NEWS_IND = 'FETCHED_NEWS_IND';
//export const ERROR_IND = 'ERROR_IND';

//SPTS
export const FETCHING_NEWS_SPTS = 'FETCHING_NEWS_SPTS';
export const FETCHED_NEWS_SPTS = 'FETCHED_NEWS_SPTS';
//export const ERROR_SPTS = 'ERROR_SPTS';

// WLD
export const FETCHING_NEWS_WLD = 'FETCHING_NEWS_WLD';
export const FETCHED_NEWS_WLD = 'FETCHED_NEWS_WLD';